#!/usr/bin/env bash
#
#                  Caddy Helper Script
#
#   Homepage: https://github.com/niklas-heer/chelper
#   Issues:   https://github.com/niklas-heer/chelper/issues
#   Requires: bash, curl or wget and systemd
#
# Hi! This is a small script that helps you with common tasks with caddy.
# Use it like this:
#

#########################
# The command line help #
#########################
chelper_display_help() {
	echo "Usage: chelper [option...]" >&2
	echo
	echo "   -h, help           Displays this help page."
	echo "   -u, update         Updates caddy with all the wanted plugins."
	echo "   -f, fix            Fixes systemd related issue with caddy."
	echo
}

# Source: https://gist.github.com/epiloque/8cf512c6d64641bde388
parse_yaml() {
    local prefix=$2
    local s
    local w
    local fs
    s='[[:space:]]*'
    w='[a-zA-Z0-9_]*'
    fs="$(echo @|tr @ '\034')"
    sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s[:-]$s\(.*\)$s\$|\1$fs\2$fs\3|p" "$1" |
    awk -F"$fs" '{
    indent = length($1)/2;
    vname[indent] = $2;
    for (i in vname) {if (i > indent) {delete vname[i]}}
        if (length($3) > 0) {
            vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
            printf("%s%s%s=(\"%s\")\n", "'"$prefix"'",vn, $2, $3);
        }
    }' | sed 's/_=/+=/g'
}


# get config
eval $(parse_yaml chelper_config.yml "config_")

# test yaml content
# plugins="$(printf '%s,' ${config_chelper_plugins[@]})"
# echo ${plugins::-1} # cut last char

chelper_fix() {
	chown $CHELPER_CADDY_USER:$CHELPER_CADDY_USER $CHELPER_CADDY_PATH
	sudo setcap cap_net_bind_service=+ep $CHELPER_CADDY_PATH &>/dev/null
}

##################
# Helper command #
##################
case "$1" in
	-h | help)
		chelper_display_help
		;;
	-u | update)
		curl https://getcaddy.com | bash -s $CHELPER_CADDY_PLUGINS
		chelper_fix
		;;
	-f | fix)
		chelper_fix
		;;
	-*)
		echo "Error: Unknown option: $1" >&2
		;;
	*)  # No more options
		chelper_display_help
		;;
esac
