chelper:
  user: caddy
  bin: /usr/local/bin/caddy
  config: /etc/caddy/Caddyfile
  plugins:
    - git
    - filemanager
    - cors
    - hugo
    - ipfilter
    - locale
    - mailout
    - minify
    - ratelimit
    - realip
    - search
    - upload
